# ============================================================================
# FRONTEND-ONLY PRODUCTION MODE
# ============================================================================
# ⚠️  For full-stack deployment (Frontend + Backend + DB), 
#     use the docker-compose.yml in the AISA_Backend directory instead!
# 
# This file is for deploying ONLY the frontend when:
# - Backend is deployed separately (different server/service)
# - You need standalone frontend container
#
# Usage: docker-compose up -d
# ============================================================================

services:
  # React Frontend
  aisa-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aisa-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      # ⚠️  UPDATE THIS: Point to your actual backend URL
      # Examples:
      #   - http://your-backend-server.com:8000
      #   - https://api.yourdomain.com
      #   - http://host.docker.internal:8000 (if backend on same host)
      - REACT_APP_API_URL=http://host.docker.internal:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"
